@echo off
echo Running Migration...
node server/update_chat_audio_schema.js > server/migration.log 2>&1
echo Running Schema Check...
node server/verify_audio_schema.js > server/schema.log 2>&1
echo Running Files Check...
node server/verify_files.js > server/files.log 2>&1
echo Done.
